nodeLinker: node-modules
# .yarnrc.yml

# 设置同一个前缀/目录下包的源 验证有效
# 下面的设置将前缀为babel的包源指向了华为源
# 如果babel前缀的包依赖了其他非babel前缀的包，那么这些非babel的包将不适用该规则
# "npmScopes":
#   # babel不能以@为开头
#   "babel":
#     "npmRegistryServer": "https://mirrors.huaweicloud.com/repository/npm/"
enableMirror: true  # 启用镜像
# # # 如果上面的前缀规则没有匹配到，则使用这里的源
npmRegistryServer: "https://registry.npmmirror.com"
# npmRegistryServer: "https://npmmirror.com/"  # 主仓库镜像
# npmScopes:
#   electron:
#     npmRegistryServer: "https://registry.npmmirror.com/binary.html?path=electron/"  # Electron 专用镜像[7,10](@ref)
# # npmRegistryServer: "https://registry.yarnpkg.com"

